### ISSUE TITLE
"All.v" is not compilable.

### ISSUE THREAD

**Issue by ghost** [clarus/falso#1]
Hi,

After downloading "All.v", I have tried to compile it:

  coqc All.v

I am getting:

  File "./.coq-native/NAll.native", line 14, characters 5-11510:
  Error: Too many non-constant constructors
       -- maximum is 246 non-constant constructors
  Error: Could not compile the library to native code. Skipping.

I am not sure where does this fall (feature / bug / missing feature, perhaps) but I report it out of curiousity.

**Comment by clarus** [comment]
Thanks. This bug concerns the development versions of Coq. It seems to be a problem in the error message, because `coqc` returns `0`:

```
coqc All.v
echo $?
```

so that `All.v` is still compiled to a valid `All.vo` and can be imported by an other project. I reported this bug [here](https://coq.inria.fr/bugs/show_bug.cgi?id=4158).

**Comment by ghost** [comment]
For the Coq-trunk, what you say does no longer seem to be true.
Is that right?

I mean, when I pull the trunk, try to compile "All.v", I am getting a different error message now:

  File "./All.v", line 270, characters 2-65:
  Error: In environment
  H : is_256 (C_256 0) = true
  Unable to unify "false" with "true".

and the corresponding exit status is 0 (not 1 as before).

No All.vo file is generated this time.

**Comment by clarus** [comment]
Yes, the trunk version of Coq has just been corrected. I changed the README description to match this fact. Thanks for your remark.
